services:
  web:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "9080:80"
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: docker
      WORDPRESS_DB_PASSWORD: docker
      WORDPRESS_DB_NAME: docker
    depends_on:
      - database
    volumes:
      - files:/var/www/html:rw
  database:
    image: mariadb:10.6
    volumes:
      - database:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - database
    ports:
      - "9081:80"
    environment:
      PMA_USER: docker
      PMA_PASSWORD: docker
      PMA_PORT: 3306
      PMA_HOST: database
volumes:
  database:
  files:
